[package]
name = "orbithunter"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.33.2"
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1", features = ["full"] }
regex = "1.11.1"
julian_day_converter = "0.4.4"
chrono = "0.4.39"
itertools = "0.14.0"
csv = "1.3.1"
serde = { version = "1.0", features = ["derive"] }
